### ISSUE TITLE
Not clear README.md

### ISSUE THREAD

**Issue by MortdaLtfe** [DanielHe4rt/nestjs-task-manager#27]
I'm facing difficulty at endpoints and what's the whole project does means, i suggest to create your own `README.md` file, so devs able to understand

**Comment by danielhe4rt** [comment]
This project weren't supposed to be something production ready. I made it to test NestJS for the first time.

But yes, you're right. Should have a documentation.

**Comment by MortdaLtfe** [comment]
to  be honest i didn't  expect that, or i just was thinking in something else...
